
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class MenuPrincipal extends javax.swing.JFrame {

    Operacion Opera = new Operacion();

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();

        CompletarTabla();
    }

    private void CompletarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) jtbl_verClientes.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);      //Para borrar los registros anteriores     
        }
        for (int i = 1; i <= Opera.NroReg-1; i++) {
            modelo.addRow(new Object[]{Opera.Cuenta[i].NombreUsuario, Opera.Cuenta[i].Rut, Opera.Cuenta[i].Contraseña, Opera.Cuenta[i].SaldoAhorro,
                Opera.Cuenta[i].SaldoCorriente});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jtxt_menuAhorro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxt_nombreClientetabla = new javax.swing.JTextField();
        jtxt_rutClientetabla = new javax.swing.JTextField();
        jtxt_ctaAhorrotabla = new javax.swing.JTextField();
        jtxt_ctaCorrientetabla = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jbtn_registrar = new javax.swing.JButton();
        jbtn_limpiar = new javax.swing.JButton();
        jtxt_contraseñaCliTabla = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbl_verClientes = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmi_ahorro = new javax.swing.JMenuItem();
        jmi_corriente = new javax.swing.JMenuItem();
        jmi_salir = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco Punto Salvador - Menú Principal");

        jtxt_menuAhorro.setBackground(new java.awt.Color(153, 204, 255));
        jtxt_menuAhorro.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bienvenido a tu banco");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estrellas (1).png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre Cliente:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Rut Cliente:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Contraseña:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cuenta Corriente:");

        jtxt_nombreClientetabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nombreClientetablaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Cuenta de Ahorro:");

        jbtn_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprobado.png"))); // NOI18N
        jbtn_registrar.setText("Registrar y Actualizar");
        jbtn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_registrarActionPerformed(evt);
            }
        });

        jbtn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cleaning.png"))); // NOI18N
        jbtn_limpiar.setText("Limpiar");
        jbtn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jtxt_menuAhorroLayout = new javax.swing.GroupLayout(jtxt_menuAhorro);
        jtxt_menuAhorro.setLayout(jtxt_menuAhorroLayout);
        jtxt_menuAhorroLayout.setHorizontalGroup(
            jtxt_menuAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jtxt_menuAhorroLayout.createSequentialGroup()
                .addContainerGap(306, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
            .addGroup(jtxt_menuAhorroLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(jtxt_menuAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jtxt_menuAhorroLayout.createSequentialGroup()
                        .addGroup(jtxt_menuAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jtxt_menuAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxt_ctaAhorrotabla, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(jtxt_ctaCorrientetabla)
                            .addComponent(jtxt_contraseñaCliTabla)
                            .addComponent(jtxt_rutClientetabla)
                            .addComponent(jtxt_nombreClientetabla)))
                    .addGroup(jtxt_menuAhorroLayout.createSequentialGroup()
                        .addComponent(jbtn_registrar)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jtxt_menuAhorroLayout.setVerticalGroup(
            jtxt_menuAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtxt_menuAhorroLayout.createSequentialGroup()
                .addGroup(jtxt_menuAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jtxt_menuAhorroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jtxt_menuAhorroLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jtxt_menuAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_nombreClientetabla, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jtxt_menuAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_rutClientetabla, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jtxt_menuAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_contraseñaCliTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jtxt_menuAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_ctaAhorrotabla, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jtxt_menuAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_ctaCorrientetabla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(27, 27, 27)
                .addGroup(jtxt_menuAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_registrar))
                .addGap(27, 27, 27))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMACIÓN CLIENTES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jtbl_verClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtbl_verClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre Cliente", "Rut Cliente", "Contraseña", " Saldo Cta Ahorro", "Saldo Cta Corriente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_verClientes.setRowMargin(5);
        jtbl_verClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_verClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbl_verClientes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jMenu2.setText("Seleccione Cuenta");

        jmi_ahorro.setText("Cuenta Ahorro");
        jmi_ahorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ahorroActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_ahorro);

        jmi_corriente.setText("Cuenta Corriente");
        jmi_corriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_corrienteActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_corriente);

        jMenuBar1.add(jMenu2);

        jmi_salir.setText("Salir");

        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jmi_salir.add(jMenuItem4);

        jMenuBar1.add(jmi_salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtxt_menuAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtxt_menuAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_corrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_corrienteActionPerformed

        new CtaCorriente().setVisible(true);

    }//GEN-LAST:event_jmi_corrienteActionPerformed

    private void jmi_ahorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ahorroActionPerformed

        new CtaAhorro().setVisible(true);

    }//GEN-LAST:event_jmi_ahorroActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jtxt_nombreClientetablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nombreClientetablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nombreClientetablaActionPerformed

    private void jbtn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_registrarActionPerformed

        if (this.jtxt_nombreClientetabla.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Falta Nombre del Cliente");
        } else if (this.jtxt_rutClientetabla.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Falta Rut del cliente");
        } else if (this.jtxt_contraseñaCliTabla.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Falta Contraseña");
        } else if (this.jtxt_ctaAhorrotabla.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Falta Ingresar Monto");
        } else if (this.jtxt_ctaCorrientetabla.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Falta Ingresar Monto");
        } else {
            Opera.IngresarCliente(this.jtxt_nombreClientetabla.getText(), this.jtxt_rutClientetabla.getText(), this.jtxt_contraseñaCliTabla.getText(), Integer.parseInt(this.jtxt_ctaAhorrotabla.getText()), Integer.parseInt(this.jtxt_ctaCorrientetabla.getText()));

            CompletarTabla();
        }

    }//GEN-LAST:event_jbtn_registrarActionPerformed


    private void jbtn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_limpiarActionPerformed

        this.jtxt_nombreClientetabla.setText(" ");
        this.jtxt_rutClientetabla.setText(" ");
        this.jtxt_contraseñaCliTabla.setText(" ");
        this.jtxt_ctaAhorrotabla.setText(" ");
        this.jtxt_ctaCorrientetabla.setText(" ");
        this.jtxt_nombreClientetabla.requestFocus();


    }//GEN-LAST:event_jbtn_limpiarActionPerformed

    private void jtbl_verClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_verClientesMouseClicked

        String nombre = jtbl_verClientes.getValueAt(jtbl_verClientes.getSelectedRow(), 0).toString();
        this.jtxt_nombreClientetabla.setText(nombre);

        String rut = jtbl_verClientes.getValueAt(jtbl_verClientes.getSelectedRow(), 1).toString();
        this.jtxt_rutClientetabla.setText(rut);

        String psword = jtbl_verClientes.getValueAt(jtbl_verClientes.getSelectedRow(), 2).toString();
        this.jtxt_contraseñaCliTabla.setText(psword);

        String cuentaahorro = jtbl_verClientes.getValueAt(jtbl_verClientes.getSelectedRow(), 3).toString();
        this.jtxt_ctaAhorrotabla.setText(cuentaahorro);

        String cuentacte = jtbl_verClientes.getValueAt(jtbl_verClientes.getSelectedRow(), 4).toString();
        this.jtxt_ctaCorrientetabla.setText(cuentacte);


    }//GEN-LAST:event_jtbl_verClientesMouseClicked

  /**
  * @param args the command line arguments
     */
////    public static void main(String args[]) {
////        /* Set the Nimbus look and feel */
////        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
////        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
////         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
////         */
////        try {
////            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
////                if ("Nimbus".equals(info.getName())) {
////                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
////                    break;
////                }
////            }
////        } catch (ClassNotFoundException ex) {
////            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (InstantiationException ex) {
////            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (IllegalAccessException ex) {
////            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
////            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        }
////        //</editor-fold>
////
////        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new MenuPrincipal().setVisible(true);
////            }
////        });
////    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtn_limpiar;
    private javax.swing.JButton jbtn_registrar;
    private javax.swing.JMenuItem jmi_ahorro;
    private javax.swing.JMenuItem jmi_corriente;
    private javax.swing.JMenu jmi_salir;
    private javax.swing.JTable jtbl_verClientes;
    private javax.swing.JPasswordField jtxt_contraseñaCliTabla;
    private javax.swing.JTextField jtxt_ctaAhorrotabla;
    private javax.swing.JTextField jtxt_ctaCorrientetabla;
    private javax.swing.JPanel jtxt_menuAhorro;
    private javax.swing.JTextField jtxt_nombreClientetabla;
    private javax.swing.JTextField jtxt_rutClientetabla;
    // End of variables declaration//GEN-END:variables

}
